export const intercepted_endpoints = [
    'authorize',
    'account_security',
    'balance',
    'forget_all',
    'get_account_status',
    'get_available_accounts_to_transfer',
    'get_financial_assessment',
    'get_self_exclusion',
    'get_settings',
    'mt5_login_list',
    'new_account_real',
    'new_account_virtual',
    'new_account_wallet',
    'platform',
    'portfolio',
    'proposal_open_contract',
    'p2p_order_list',
    'statement',
    'topup_virtual',
    'trading_platform_accounts',
    'trading_platform_available_accounts',
    'transaction',
    'transfer_between_accounts',
    'wallet_migration',
] as const;
