export const intercepted_endpoints = [
    'authorize',
    'balance',
    'get_settings',
    'topup_virtual',
    'transaction',
    'statement',
    'get_available_accounts_to_transfer',
    'new_account_real',
    'new_account_virtual',
    'new_account_wallet',
    'transfer_between_accounts',
    'forget_all',
    'portfolio',
    'get_account_status',
    'proposal_open_contract',
    'wallet_migration',
] as const;
